---

- Administración:

    - Dozzle:
        href: http://dozzle.jarvis.local
        description: Logs de contenedores Docker

    - Homepage:
        href: http://homepage.jarvis.local
        description: Dashboard principal del HomeLab

    - Portainer:
        href: http://portainer.jarvis.local
        description: Administración de Docker

    - Nginx Proxy Manager:
        href: http://192.168.0.24:81
        description: Reverse Proxy

- Monitoreo:

    - Uptime Kuma:
        href: http://uptime.jarvis.local
        description: Monitoreo de disponibilidad
